"""Guard tests for the header-signature based source registry.

Discovery matches input files by the SHAPE of their header row, never by
filename. That makes signature collisions the primary failure mode: if one
source's required headers are a subset of another source's header set, a
single file can satisfy both definitions and be resolved ambiguously (or
silently mis-assigned).

These tests pin the invariants that keep discovery unambiguous, so that a
future change to any signature fails loudly here rather than silently
producing wrong business numbers.
"""

from __future__ import annotations

import itertools
import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from modules.source_registry import SOURCE_DEFINITIONS  # noqa: E402


def _normalize(header: object) -> str:
    """Mirror the tolerant normalization used during discovery."""
    text = str(header).replace("_", " ").replace("-", " ")
    return " ".join(text.split()).casefold()


def _normalized(headers) -> set[str]:
    return {_normalize(header) for header in headers}


def _all_headers(definition) -> set[str]:
    return _normalized(definition.required_headers) | _normalized(definition.optional_headers)


class TestNoSignatureCollisions(unittest.TestCase):
    def test_no_source_signature_is_a_subset_of_another(self):
        """A source whose required headers are a subset of another source's
        full header set can be matched ambiguously during discovery."""
        for first, second in itertools.permutations(SOURCE_DEFINITIONS.values(), 2):
            required = _normalized(first.required_headers)
            with self.subTest(source=first.logical_name, against=second.logical_name):
                self.assertFalse(
                    required.issubset(_all_headers(second)),
                    f"'{first.logical_name}' required headers {sorted(required)} are a "
                    f"subset of '{second.logical_name}' headers -- discovery is ambiguous.",
                )

    def test_every_source_has_a_discriminator_against_every_other(self):
        for name, definition in SOURCE_DEFINITIONS.items():
            for other_name, other in SOURCE_DEFINITIONS.items():
                if name == other_name:
                    continue
                discriminators = _normalized(definition.required_headers) - _all_headers(other)
                with self.subTest(source=name, against=other_name):
                    self.assertTrue(
                        discriminators,
                        f"'{name}' has no discriminating required header against '{other_name}'.",
                    )


class TestSalesSummaryIsNotAnInput(unittest.TestCase):
    def test_sales_summary_is_not_a_registered_source(self):
        """Sales Summary is GENERATED by this pipeline as an OUTPUT
        (Sales_Summary.xlsx / the POB "Summary" sheet). It must never be
        registered as an input source -- doing so previously collided with the
        Morning Completed Order Book, which contains its entire signature
        (Sales Order No. + NDC Code + Lookup)."""
        self.assertNotIn("sales_summary", SOURCE_DEFINITIONS)


class TestQuantitySources(unittest.TestCase):
    """The Morning Completed Order Book and the Upload Sheet are the two
    mutually-exclusive sources of the Sales Order Qty used to adjust UPS
    Inventory. Exactly one is used per run; the pair is enforced at runtime
    in derived_dataset_manager.run_phase2()."""

    def test_both_quantity_sources_are_registered(self):
        self.assertIn("morning_completed_orderbook", SOURCE_DEFINITIONS)
        self.assertIn("upload_sheet", SOURCE_DEFINITIONS)

    def test_both_quantity_sources_are_individually_optional(self):
        # Neither is individually mandatory -- only the PAIR is required, and
        # that rule cannot be expressed by the per-source `mandatory` flag.
        self.assertFalse(SOURCE_DEFINITIONS["morning_completed_orderbook"].mandatory)
        self.assertFalse(SOURCE_DEFINITIONS["upload_sheet"].mandatory)

    def test_both_quantity_sources_supply_ndc_and_sales_order_qty(self):
        for name in ("morning_completed_orderbook", "upload_sheet"):
            headers = _normalized(SOURCE_DEFINITIONS[name].required_headers)
            with self.subTest(source=name):
                self.assertIn(_normalize("NDC Code"), headers)
                self.assertIn(_normalize("Sales Order Qty"), headers)

    def test_morning_orderbook_discriminators_are_unique(self):
        """"UPS Inventory" and "Sales Value (FC)" must appear in no other
        source, since they are what separate the morning file from both the
        Orderbook and the Upload Sheet."""
        morning = SOURCE_DEFINITIONS["morning_completed_orderbook"]
        self.assertIn(_normalize("UPS Inventory"), _normalized(morning.required_headers))
        self.assertIn(_normalize("Sales Value (FC)"), _normalized(morning.required_headers))

        for name, definition in SOURCE_DEFINITIONS.items():
            if name == "morning_completed_orderbook":
                continue
            with self.subTest(against=name):
                self.assertNotIn(_normalize("UPS Inventory"), _all_headers(definition))
                self.assertNotIn(_normalize("Sales Value (FC)"), _all_headers(definition))

    def test_reason_code_discriminates_upload_sheet_from_orderbook(self):
        """"Reason Code" is the SOLE discriminator between the Upload Sheet and
        the Orderbook. If the Orderbook export ever gains a Reason Code column,
        upload_sheet needs an additional discriminating required header."""
        upload = SOURCE_DEFINITIONS["upload_sheet"]
        orderbook = SOURCE_DEFINITIONS["orderbook"]
        discriminators = _normalized(upload.required_headers) - _all_headers(orderbook)
        self.assertIn(_normalize("Reason Code"), discriminators)


class TestHeaderNormalization(unittest.TestCase):
    def test_spelling_variants_are_equivalent(self):
        canonical = _normalize("Reason Code")
        for variant in ("Reason code", "REASON CODE", "Reason_Code", "  Reason  Code ", "reason-code"):
            with self.subTest(variant=variant):
                self.assertEqual(_normalize(variant), canonical)

    def test_packsize_spacing_variants_stay_distinct(self):
        """The Orderbook uses "PackSize(MOQ)" (unspaced) while the Morning
        Completed Order Book uses "Pack Size (MOQ)" (spaced). Normalization
        must NOT collapse these into one another, or the morning file could
        match the orderbook signature."""
        self.assertNotEqual(_normalize("PackSize(MOQ)"), _normalize("Pack Size (MOQ)"))

    def test_open_order_total_padding_is_normalized(self):
        """open_order_summary requires " Total " with surrounding spaces."""
        self.assertEqual(_normalize(" Total "), "total")


if __name__ == "__main__":
    unittest.main()
